# Generated by Django 2.0.7 on 2018-12-13 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='大类代码')),
                ('name', models.CharField(max_length=100, verbose_name='大类名称')),
            ],
            options={
                'verbose_name': '大类类型',
                'verbose_name_plural': '大类类型',
                'db_table': 'bigtype',
            },
        ),
        migrations.CreateModel(
            name='ChildType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='子类代码')),
                ('name', models.CharField(max_length=100, verbose_name='子类名称')),
            ],
            options={
                'verbose_name': '子类类型',
                'verbose_name_plural': '子类类型',
                'db_table': 'childtype',
            },
        ),
        migrations.CreateModel(
            name='MiddleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='中类代码')),
                ('name', models.CharField(max_length=100, verbose_name='中类名称')),
                ('big', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bigs', to='type.BigType')),
            ],
            options={
                'verbose_name': '中类类型',
                'verbose_name_plural': '中类类型',
                'db_table': 'middletype',
            },
        ),
        migrations.CreateModel(
            name='SmallType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='小类代码')),
                ('name', models.CharField(max_length=100, verbose_name='小类名称')),
                ('middle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='middle', to='type.MiddleType')),
            ],
            options={
                'verbose_name': '小类类型',
                'verbose_name_plural': '小类类型',
                'db_table': 'smalltype',
            },
        ),
        migrations.AddField(
            model_name='childtype',
            name='small',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='small', to='type.SmallType'),
        ),
    ]
